<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_submitButton</name>
   <tag></tag>
   <elementGuidId>6d48367a-aabf-4b4d-b982-d96dfce52283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | id(&quot;submitButton&quot;)) = count(id(&quot;submitButton&quot;))][count(. | //*[@id = 'submitButton']) = count(//*[@id = 'submitButton'])][count(. | //*[@class = 'labkey-button']) = count(//*[@class = 'labkey-button'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
   </webElementProperties>
</WebElementEntity>
