<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_HT01021A04_Perfect_523.58_6.53.jpg</name>
   <tag></tag>
   <elementGuidId>d1d2d3cf-b3ba-4769-affe-89567527cb2c</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HT01021A04_Perfect_523.58_6.91.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td/div/div/div/span[text()=&quot;HT01021A04_Perfect_523.58_6.53.jpg&quot;]/parent::div/parent::div/parent::div/parent::td/preceding-sibling::td/preceding-sibling::td/div/div</value>
   </webElementProperties>
</WebElementEntity>
