<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_HT01021A05</name>
   <tag></tag>
   <elementGuidId>cde48165-084f-410c-9895-d7c10014436b</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HT01021A05_NoNR_0.00_0.00.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td/div/div/div/span[text()=&quot;HT01021A05_NoNR_0.00_0.00.jpg&quot;]/parent::div/parent::div/parent::div/parent::td/preceding-sibling::td/preceding-sibling::td/div/div</value>
   </webElementProperties>
</WebElementEntity>
