<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Assays</name>
   <tag></tag>
   <elementGuidId>790b9e2d-bbc0-491e-93eb-12e569c41794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div/div/div/span/a[count(. | //a[(contains(text(), 'Assays') or contains(., 'Assays')) and @href = '/project/Optides/HTProduction/Assays/begin.view?']) = count(//a[(contains(text(), 'Assays') or contains(., 'Assays')) and @href = '/project/Optides/HTProduction/Assays/begin.view?'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assays</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project/Optides/HTProduction/Assays/begin.view?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div/div/div/span/a</value>
   </webElementProperties>
</WebElementEntity>
