<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_CHEMProduction_Assays</name>
   <tag></tag>
   <elementGuidId>842ac78c-4fc5-4a9c-8368-123df8aa47a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr/td/a[text()=&quot;Assay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr/td/a[text()=&quot;Assay&quot;]</value>
   </webElementProperties>
</WebElementEntity>
