<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_OTDProduction_Assays</name>
   <tag></tag>
   <elementGuidId>dbc5bf44-8b20-446e-b53d-2ad0a7f0049a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[text() = 'Assays']) = count(//*[text() = 'Assays'])][count(. | //*[@href = '/project/Optides/OTDProduction/Assays/begin.view?']) = count(//*[@href = '/project/Optides/OTDProduction/Assays/begin.view?'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assays</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project/Optides/OTDProduction/Assays/begin.view?</value>
   </webElementProperties>
</WebElementEntity>
