<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paging</name>
   <tag></tag>
   <elementGuidId>485fd9d1-9959-48bb-addb-58b63676bf93</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lk-region-14811-header&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;labkey-button-bar&quot;]/span[9]/a[@class=&quot;labkey-menu-button&quot;]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paging</value>
   </webElementProperties>
</WebElementEntity>
