<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insert</name>
   <tag></tag>
   <elementGuidId>d624bc3d-d3f2-478d-aff2-139d2a159c63</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lk-region-14305-header&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;labkey-button-bar&quot;]/span[5]/a[@class=&quot;labkey-menu-button&quot;]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insert</value>
   </webElementProperties>
</WebElementEntity>
