<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_studyDescription</name>
   <tag></tag>
   <elementGuidId>3f67def1-7bb1-46cb-bb25-199280d5a923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[count(. | //*[@name = 'studyDescription']) = count(//*[@name = 'studyDescription'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>studyDescription</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lk-region-544-form&quot;)/table[1]/tbody[1]/tr[1]/td[2]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
