<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_TEST_insertHomologuesThroughPipeline.xlsx</name>
   <tag></tag>
   <elementGuidId>7495cbc9-d6f2-4f2a-9ea7-25e2da227139</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST_insertHomologuesThroughPipeline.xlsx</value>
   </webElementProperties>
</WebElementEntity>
