<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_TEST_insertVariantsThroughPipeline.xlsx</name>
   <tag></tag>
   <elementGuidId>ba7b2534-6608-4d44-b3e0-b8dc892af57d</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST_insertVariantsThroughPipeline.xlsx</value>
   </webElementProperties>
</WebElementEntity>
