<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_TESTinsertConstructsThroughPipeline.xml</name>
   <tag></tag>
   <elementGuidId>6e0ed9f4-b0e1-402a-8ab2-c9644a0e489a</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST_insertConstructsThroughPipeline.xlsx</value>
   </webElementProperties>
</WebElementEntity>
