<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_newChemProducts_input.xlsx</name>
   <tag></tag>
   <elementGuidId>84cfe4e0-1ffc-4251-9c4c-235a1576ddb9</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newChemProducts_input.xlsx</value>
   </webElementProperties>
</WebElementEntity>
