<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ht_dna_generateOrder4Kata</name>
   <tag></tag>
   <elementGuidId>53492a07-f536-432f-ad76-21a1191308a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[contains(.,'ht_dna_generateOrder4Katalon.xlsx')]) = count(//*[contains(.,'ht_dna_generateOrder4Katalon.xlsx')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ht_dna_generateOrder4Katalon.xlsx</value>
   </webElementProperties>
</WebElementEntity>
