<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test_GenScript_HT_DNA_DeliveryFile.xlsx</name>
   <tag></tag>
   <elementGuidId>1443fc12-b34d-4df4-8afb-00fc1c638c46</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test_GenScript_HT_DNA_DeliveryFile.xlsx</value>
   </webElementProperties>
</WebElementEntity>
