<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ht_dna_generateOrder4Kata</name>
   <tag></tag>
   <elementGuidId>53492a07-f536-432f-ad76-21a1191308a5</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext4-ext-gen2314&quot;)/div[@class=&quot;x4-grid-cell-inner&quot;]/div[1]/div[2]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ht_dna_generateOrder4Katalon.xlsx</value>
   </webElementProperties>
</WebElementEntity>
